### ISSUE TITLE
Any difference with fusion?

### ISSUE THREAD

**Issue by smeijer** [cult-of-coders/ddp-silencer#1]
Is there any difference between this package and [Fusion](https://github.com/cult-of-coders/fusion)? `ddp-silencer` feels a bit like "Fusion v2". 

Should Fusion be archived / forwarded to here, or does it have something that this package does not have?

**Comment by theodorDiaconu** [comment]
Sorry but I do not remember the real reason to be frank. I think it was due to some ddp upgrades they made on Meteor.
